services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ecomm
      POSTGRES_PASSWORD: ecomm_dev_password
      POSTGRES_DB: ecommderce
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ecomm -d ecommderce']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: